version: '3.8'

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  face-server:
    build: .
    container_name: deepface-api
    network_mode: host
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
